/*
 * This file is generated by jOOQ.
 */
package io.amplicode.spring.jdbc.service.owner.impl.jooq.generate;


import io.amplicode.spring.jdbc.service.owner.impl.jooq.generate.tables.Owners;
import io.amplicode.spring.jdbc.service.owner.impl.jooq.generate.tables.Pets;
import io.amplicode.spring.jdbc.service.owner.impl.jooq.generate.tables.Types;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.owners</code>.
     */
    public static final Owners OWNERS = Owners.OWNERS;

    /**
     * The table <code>public.pets</code>.
     */
    public static final Pets PETS = Pets.PETS;

    /**
     * The table <code>public.types</code>.
     */
    public static final Types TYPES = Types.TYPES;
}
